services:
  wifimap:
    image: ghcr.io/znerox/wifimap:latest
    hostname: wifimap
    container_name: wifimap
    restart: unless-stopped
    ports:
        - 80:80
    depends_on:
        - wifimap-mysql
    environment:
        - server=wifimap-mysql
        - database=wifimap
        - username=root
        - password=password
        - environment=release
        - google_maps_api_key=YOUR_API_KEY


  wifimap-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: wifimap-phpmyadmin
    container_name: wifimap-phpmyadmin
    restart: unless-stopped
    ports:
        - 8080:80
    environment:
        PMA_HOST: wifimap-mysql
    depends_on:
        - wifimap-mysql

  wifimap-mysql:
    image: mysql:8.4
    hostname: wifimap-mysql
    container_name: wifimap-mysql
    restart: unless-stopped
    volumes:
        - ./wifimap_db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
