name: Docker Image CI

on:
  push:
    branches: [ "master" ]

  schedule:
    - cron: "15 12 * * 1"

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v7

    - name: Set up QEMU
      run: docker run --privileged --rm tonistiigi/binfmt --install arm64

    - name: Set up buildx builder
      run: docker buildx create --use --driver docker-container
    
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build and push the Docker image
      run: >
        docker buildx build wifimap
        --platform linux/amd64,linux/arm64
        --tag ghcr.io/znerox/wifimap:latest
        --push
